"use client";

import { useEffect, useRef, useState } from "react";
import { useChatStore } from "@/lib/chat-store";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";
import { detectBrowserLanguage } from "@/lib/languages";
import Sidebar from "./Sidebar";
import WelcomeScreen from "./WelcomeScreen";
import MessageThread from "./MessageThread";
import InputBar from "./InputBar";
import OnboardingTour from "./OnboardingTour";
import PreviewDrawer from "./PreviewDrawer";
import AgentSwitcher from "./AgentSwitcher";
import { getModel } from "@/lib/models";
import Image from "next/image";
import {
  Share2, MoreHorizontal, Menu,
  Copy, Download, Check, Pencil, Trash2, HelpCircle,
} from "lucide-react";
import { cn } from "@/lib/utils";

function conversationToMarkdown(title: string, messages: { role: string; content: string }[]): string {
  const out: string[] = [`# ${title}`, ""];
  for (const m of messages) {
    out.push(m.role === "user" ? "### You" : "### Reverb");
    out.push("");
    out.push(m.content);
    out.push("");
  }
  out.push("---");
  out.push(`Generated by Reverb · ${new Date().toLocaleString()}`);
  return out.join("\n");
}

export default function ChatLayout() {
  const conv = useChatStore((s) => s.activeConversation());
  const selectedModel = useChatStore((s) => s.selectedModel);
  const deleteConversation = useChatStore((s) => s.deleteConversation);
  const renameConversation = useChatStore((s) => s.renameConversation);
  const hydrateFromServer = useChatStore((s) => s.hydrateFromServer);
  const unbind = useChatStore((s) => s.unbind);

  // Cross-device chat sync: pull this user's conversations from Supabase
  // on sign-in and merge with anything localStorage still has. Re-subscribes
  // on auth state changes so a sign-out wipes the in-memory list and a
  // fresh sign-in re-hydrates from the new user's rows.
  useEffect(() => {
    const sb = createSupabaseBrowserClient();
    let cancelled = false;

    sb.auth.getUser().then(({ data: { user } }) => {
      if (cancelled) return;
      if (user) {
        const current = useChatStore.getState().userId;
        if (current !== user.id) void hydrateFromServer(user.id);
      }
    });

    // Supabase fires onAuthStateChange on FOUR distinct kinds of events:
    //   INITIAL_SESSION   — on subscribe + whenever the tab regains focus
    //                       and the client re-checks the session
    //   SIGNED_IN         — actual sign-in transition
    //   SIGNED_OUT        — actual sign-out transition
    //   TOKEN_REFRESHED   — background JWT refresh (happens every ~hour
    //                       AND whenever the tab regains focus if the
    //                       session is close to expiry)
    //   USER_UPDATED      — user metadata change
    //   PASSWORD_RECOVERY — password-reset flow
    //
    // Treating every event as a sign-in (the old code) meant tabbing away
    // from Reverb and coming back wiped the user's active conversation —
    // hydrateFromServer resets activeId so the chat appeared "closed"
    // every time INITIAL_SESSION or TOKEN_REFRESHED fired on tab focus.
    // Only re-hydrate when the bound user actually changes (different
    // user signed in), and only unbind on a real SIGNED_OUT.
    const { data: sub } = sb.auth.onAuthStateChange((evt, session) => {
      if (cancelled) return;
      if (evt === "SIGNED_OUT") {
        unbind();
        return;
      }
      if (evt === "SIGNED_IN" && session?.user) {
        const current = useChatStore.getState().userId;
        if (current !== session.user.id) void hydrateFromServer(session.user.id);
      }
      // INITIAL_SESSION / TOKEN_REFRESHED / USER_UPDATED → no-op
      // (the getUser() above already handled the initial hydrate, and
      // ongoing token refreshes don't change which user is bound).
    });

    return () => {
      cancelled = true;
      sub.subscription.unsubscribe();
    };
  }, [hydrateFromServer, unbind]);

  // First-load browser-language detection. Runs once per browser instance
  // — the languageInitialized flag is persisted to localStorage so a user
  // who explicitly picked "Auto" doesn't get auto-overridden on every page
  // load. Server-safe: navigator.language is only read inside the effect,
  // which never runs during SSR. Maps the BCP-47 browser tag (e.g.
  // "hi-IN", "pt-BR", "es-MX") to a SUPPORTED_LANGUAGES code via exact-
  // then-base-tag matching; falls back to leaving outputLanguage as "auto"
  // (and marking initialized) when the browser is in an unsupported
  // language so the LANGUAGE CONTRACT's auto-match behavior still applies.
  useEffect(() => {
    const state = useChatStore.getState();
    if (state.languageInitialized) return;
    const detected = detectBrowserLanguage(
      typeof navigator !== "undefined" ? navigator.language : undefined
    );
    if (detected !== "auto") {
      state.setOutputLanguage(detected);
    } else {
      state.markLanguageInitialized();
    }
  }, []);

  const current = getModel(selectedModel);
  const [mobileNavOpen, setMobileNavOpen] = useState(false);
  const [shareOpen, setShareOpen] = useState(false);
  const [moreOpen, setMoreOpen] = useState(false);
  const [copiedShare, setCopiedShare] = useState(false);
  const [renaming, setRenaming] = useState(false);
  const [renameValue, setRenameValue] = useState("");
  const shareRef = useRef<HTMLDivElement>(null);
  const moreRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (shareRef.current && !shareRef.current.contains(e.target as Node)) setShareOpen(false);
      if (moreRef.current && !moreRef.current.contains(e.target as Node)) setMoreOpen(false);
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  const hasConv = !!conv && conv.messages.length > 0;

  const copyAsMarkdown = async () => {
    if (!conv) return;
    const md = conversationToMarkdown(conv.title, conv.messages);
    await navigator.clipboard.writeText(md);
    setCopiedShare(true);
    setTimeout(() => setCopiedShare(false), 1500);
  };

  const downloadAsMarkdown = () => {
    if (!conv) return;
    const md = conversationToMarkdown(conv.title, conv.messages);
    const safeTitle = conv.title.replace(/[^a-z0-9-_]+/gi, "-").slice(0, 50);
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `reverb-${safeTitle}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setShareOpen(false);
  };

  const nativeShare = async () => {
    if (!conv) return;
    const md = conversationToMarkdown(conv.title, conv.messages);
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Reverb — ${conv.title}`,
          text: md.slice(0, 4000),
        });
      } catch {}
    } else {
      await copyAsMarkdown();
    }
    setShareOpen(false);
  };

  const startRename = () => {
    if (!conv) return;
    setRenameValue(conv.title);
    setRenaming(true);
    setMoreOpen(false);
  };

  const commitRename = () => {
    if (conv && renameValue.trim()) {
      renameConversation(conv.id, renameValue.trim().slice(0, 100));
    }
    setRenaming(false);
  };

  const deleteCurrent = () => {
    if (!conv) return;
    if (!confirm("Delete this conversation? This can't be undone.")) return;
    deleteConversation(conv.id);
    setMoreOpen(false);
  };

  const showTour = () => {
    localStorage.removeItem("reverb_onboarded_v2");
    // Wipe v1 too so the "Show tour again" path stays clean after the v2 rollout.
    localStorage.removeItem("reverb_onboarded_v1");
    window.location.reload();
  };

  return (
    <div className="flex h-screen overflow-hidden bg-[var(--reverb-bg-app)]">
      <OnboardingTour />
      <Sidebar mobileOpen={mobileNavOpen} onMobileClose={() => setMobileNavOpen(false)} />

      <main className="flex-1 flex flex-col min-w-0 min-h-0 relative">
        <div
          className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[300px] pointer-events-none opacity-40"
          style={{
            background: "radial-gradient(ellipse at top, rgba(193, 74, 42, 0.08) 0%, transparent 70%)",
          }}
        />

        {/* Top bar */}
        <header
          className="h-14 flex items-center justify-between px-4 sm:px-6 shrink-0 relative z-20 gap-2"
          style={{
            background: "rgba(250, 248, 245, 0.85)",
            backdropFilter: "blur(12px)",
            borderBottom: "1px solid var(--reverb-border-soft)",
          }}
        >
          <div className="flex items-center gap-2 min-w-0 flex-1">
            <button
              onClick={() => setMobileNavOpen(true)}
              className="md:hidden p-2 -ml-2 rounded-lg text-[var(--reverb-text-secondary)] hover:bg-white hover:shadow-[var(--reverb-shadow-sm)] active:scale-95 transition-all"
              title="Open menu"
            >
              <Menu size={17} />
            </button>
            <div className="flex items-center gap-2 min-w-0">
              <span className="inline-flex items-center justify-center w-5 h-5 rounded bg-white border border-[var(--reverb-border-soft)] p-0.5 shrink-0">
                <Image src="/reverb-logo.png" alt="Reverb" width={40} height={12} className="w-full h-auto object-contain" />
              </span>
              {renaming && conv ? (
                <input
                  autoFocus
                  value={renameValue}
                  onChange={(e) => setRenameValue(e.target.value)}
                  onBlur={commitRename}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") commitRename();
                    if (e.key === "Escape") setRenaming(false);
                  }}
                  className="text-[13px] font-medium bg-white border border-[var(--reverb-accent)] rounded-md px-2 py-0.5 focus:outline-none w-full max-w-[260px] sm:w-60"
                />
              ) : (
                <span className="text-[13px] text-[var(--reverb-text-secondary)] font-medium truncate">
                  {conv ? conv.title : current.label}
                </span>
              )}
            </div>
            {/* Agent switcher — sits between the title and the right-side
                actions. Hides itself when the user has no agents yet. */}
            <AgentSwitcher />
          </div>

          <div className="flex items-center gap-1 shrink-0">
            {/* Share */}
            <div ref={shareRef} className="relative">
              <button
                onClick={() => hasConv && setShareOpen((o) => !o)}
                disabled={!hasConv}
                className={cn(
                  "hidden sm:flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[13px] font-medium transition-all duration-200 active:scale-95",
                  hasConv
                    ? "text-[var(--reverb-text-secondary)] hover:bg-white hover:shadow-[var(--reverb-shadow-sm)] hover:text-[var(--reverb-text-primary)]"
                    : "text-[var(--reverb-text-tertiary)] cursor-not-allowed opacity-50"
                )}
              >
                <Share2 size={13} strokeWidth={2.2} /> Share
              </button>
              <button
                onClick={() => hasConv && setShareOpen((o) => !o)}
                disabled={!hasConv}
                className={cn(
                  "sm:hidden p-2 rounded-lg transition-all duration-200 active:scale-95",
                  hasConv
                    ? "text-[var(--reverb-text-secondary)] hover:bg-white hover:shadow-[var(--reverb-shadow-sm)]"
                    : "text-[var(--reverb-text-tertiary)] cursor-not-allowed opacity-50"
                )}
              >
                <Share2 size={14} />
              </button>

              {shareOpen && conv && (
                <div
                  className="absolute right-0 top-full mt-1.5 w-[230px] max-w-[calc(100vw-1.5rem)] rounded-xl overflow-hidden z-30 reverb-scale-in"
                  style={{
                    background: "var(--reverb-gradient-card)",
                    border: "1px solid var(--reverb-border-soft)",
                    boxShadow: "var(--reverb-shadow-xl)",
                  }}
                >
                  <div className="px-3.5 pt-3 pb-1.5">
                    <p className="text-[10px] font-semibold uppercase tracking-wider text-[var(--reverb-text-tertiary)]">
                      Share conversation
                    </p>
                  </div>
                  <MenuButton onClick={copyAsMarkdown} icon={copiedShare ? Check : Copy} iconClass={copiedShare ? "text-emerald-600" : ""}>
                    {copiedShare ? "Copied to clipboard" : "Copy as markdown"}
                  </MenuButton>
                  <MenuButton onClick={downloadAsMarkdown} icon={Download}>
                    Download as .md
                  </MenuButton>
                  {typeof navigator !== "undefined" && "share" in navigator && (
                    <MenuButton onClick={nativeShare} icon={Share2}>
                      Share via…
                    </MenuButton>
                  )}
                </div>
              )}
            </div>

            {/* More */}
            <div ref={moreRef} className="relative">
              <button
                onClick={() => setMoreOpen((o) => !o)}
                className="p-2 rounded-lg text-[var(--reverb-text-secondary)] transition-all duration-200 hover:bg-white hover:shadow-[var(--reverb-shadow-sm)] active:scale-95"
              >
                <MoreHorizontal size={14} />
              </button>

              {moreOpen && (
                <div
                  className="absolute right-0 top-full mt-1.5 w-[220px] max-w-[calc(100vw-1.5rem)] rounded-xl overflow-hidden z-30 reverb-scale-in"
                  style={{
                    background: "var(--reverb-gradient-card)",
                    border: "1px solid var(--reverb-border-soft)",
                    boxShadow: "var(--reverb-shadow-xl)",
                  }}
                >
                  {hasConv && (
                    <>
                      <MenuButton onClick={startRename} icon={Pencil}>
                        Rename conversation
                      </MenuButton>
                      <MenuButton onClick={downloadAsMarkdown} icon={Download}>
                        Export as .md
                      </MenuButton>
                      <div className="h-px bg-[var(--reverb-border-soft)] mx-2" />
                    </>
                  )}
                  <MenuButton onClick={() => { setMoreOpen(false); showTour(); }} icon={HelpCircle}>
                    Show tour again
                  </MenuButton>
                  {hasConv && (
                    <>
                      <div className="h-px bg-[var(--reverb-border-soft)] mx-2" />
                      <MenuButton onClick={deleteCurrent} icon={Trash2} danger>
                        Delete conversation
                      </MenuButton>
                    </>
                  )}
                </div>
              )}
            </div>
          </div>
        </header>

        {!conv || conv.messages.length === 0 ? (
          <WelcomeScreen />
        ) : (
          <MessageThread />
        )}

        <div className="shrink-0 relative z-10">
          <InputBar />
        </div>
      </main>

      {/* Code preview drawer — slides in from the right when any code block
          triggers usePreviewStore.openPreview(). Mounted at the layout root
          so it overlays both sidebar and main panel. */}
      <PreviewDrawer />
    </div>
  );
}

function MenuButton({
  onClick, icon: Icon, iconClass = "", danger = false, children,
}: {
  onClick: () => void;
  icon: React.ComponentType<{ size: number; className?: string }>;
  iconClass?: string;
  danger?: boolean;
  children: React.ReactNode;
}) {
  return (
    <button
      onClick={onClick}
      className={cn(
        "w-full flex items-center gap-2.5 px-3.5 py-2.5 text-[13px] font-medium transition-colors text-left",
        danger
          ? "text-red-600 hover:bg-red-50"
          : "text-[var(--reverb-text-primary)] hover:bg-[#faf6ef]"
      )}
    >
      <Icon size={13} className={iconClass || (danger ? "text-red-500" : "text-[var(--reverb-text-secondary)]")} />
      <span>{children}</span>
    </button>
  );
}
